services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/portal
    depends_on:
      - php
      - mysql-portal
  php:
    container_name: php-portal-city 
    build: ./dockerfiles/php
    volumes:
      - ./src:/var/www/portal
    user: '1000:1000'
  mysql-portal:
    container_name: mysql-portal
    image: mysql
    volumes: 
      - ./mysql-portal:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    env_file:
      - mysql.env
  phpmyadmin:
    container_name: phpmyadmin-portal
    image: phpmyadmin
    ports:
      - 1500:80
    environment: 
      - PMA_HOST=mysql-portal 
    depends_on:
      - mysql-portal  

volumes:
  mysql-portal: